const nxPreset = require('@nx/jest/preset').default;

module.exports = {
  ...nxPreset,
  workerIdleMemoryLimit: '1GB',
  maxWorkers: '2',
  reporters: [
    'default',
    [
      '@jest-performance-reporter/core',
      {
        errorAfterMs: 1000,
        warnAfterMs: 500,
        logLevel: 'warn',
        maxItems: 10,
        // jsonReportPath: 'performance-report.json',
        // csvReportPath: 'performance-report.csv',
      },
    ],
  ],
  transformIgnorePatterns: [
    'node_modules/(?!remark-gfm|remark-parse|unified|unist-util-visit|react-directive|mdast-util-from-markdown|mdast-util-gfm-footnote)',
    'node_modules/(?!micromark-extension-gfm-footnote).+\\.js$',
    'node_modules/(?!remark-gfm)/index.js',
    'node_modules/(?!react-directive)/index.js',
    'node_modules/(?!@mdx-js/react)/mdx/index.js',
    'node_modules/(?!@mdxeditor)*',
    'node_modules/(?!mui-color-input)*',
    'node_modules/(?!keycloak-js)*',
  ],
  moduleNameMapper: {
    'mui-color-input': 'test/mock/ReactMarkdownMock.tsx',
    '@mdx-editor*': 'test/mock/ReactMarkdownMock.tsx',
    '@mdxeditor/gurx': 'test/mock/ReactMarkdownMock.tsx',
    '@mdx-js*': 'test/mock/ReactMarkdownMock.tsx',
    gfmFootnote: 'test/mock/ReactMarkdownMock.tsx',
    'unist-util-visit': 'test/mock/ReactMarkdownMock.tsx',
    'mdast-util-from-markdown': 'test/mock/ReactMarkdownMock.tsx',
    'mdast-util-to-string': 'test/mock/ReactMarkdownMock.tsx',
    'mdast-util-gfm-footnote': 'test/mock/ReactMarkdownMock.tsx',
    'micromark-extension-gfm-footnote': 'test/mock/ReactMarkdownMock.tsx',
    'rehype-katex': 'test/mock/ReactMarkdownMock.tsx',
    'remark-*': 'test/mock/ReactMarkdownMock.tsx',
    'react-directive': 'test/mock/ReactMarkdownMock.tsx',
    'react-markdown': 'test/mock/ReactMarkdownMock.tsx',
    'rehype-raw': 'test/mock/ReactMarkdownMock.tsx',
    'd3-color': 'node_modules/d3-color/dist/d3-color.min.js',
    'd3-array': 'node_modules/d3-array/dist/d3-array.min.js',
    'd3-geo': 'node_modules/d3-geo/dist/d3-geo.min.js',
    'd3-zoom': 'node_modules/d3-zoom/dist/d3-zoom.min.js',
    'd3-dispatch': 'node_modules/d3-dispatch/dist/d3-dispatch.min.js',
    'd3-drag': 'node_modules/d3-drag/dist/d3-drag.min.js',
    'd3-selection': 'node_modules/d3-selection/dist/d3-selection.min.js',
    'd3-interpolate': 'node_modules/d3-interpolate/dist/d3-interpolate.min.js',
    'd3-transition': 'node_modules/d3-transition/dist/d3-transition.min.js',
    'keycloak-js': 'node_modules/keycloak-js/lib/keycloak.js',
  },
};
