import axios from 'axios';
import { AuMappingService } from '../auMappingService';
import { CourseData } from '@rangeos-nx/types/cmi5';

import FormData from 'form-data';
import fs from 'fs';
import path from 'path';

export interface MoodleUploadServiceDeps {
  // This is a token generated by in moodle to use webservices
  wstoken: string;
  baseUrl: string;
}

export type MoodleCourse = {
  cmi5id: string;
  modulename: string;
  courseid?: string;
  courseName?: string;
  sectionid?: number;
};

export class MoodleUploadService {
  private wstoken: string;
  private baseUrl: string;

  constructor({ wstoken, baseUrl }: MoodleUploadServiceDeps) {
    this.wstoken = wstoken;
    this.baseUrl = baseUrl.replace(/\/$/, ''); // remove trailing slash if any
  }

  private async getCourse(courseTitle: string) {
    const url = `${this.baseUrl}/webservice/rest/server.php`;

    const params = {
      wstoken: this.wstoken,
      wsfunction: 'mod_cmi5launch_get_cmi5_course',
      moodlewsrestformat: 'json',
      modulename: courseTitle,
    };

    const response = await axios.get(url, { params });
    return response.data;
  }

  private async createCourse(course: MoodleCourse, zipPath: string) {
    const url = `${this.baseUrl}/webservice/rest/server.php`;

    const formData = new FormData();
    formData.append('file', fs.createReadStream(zipPath));
    formData.append('wstoken', this.wstoken);
    formData.append('wsfunction', 'mod_cmi5launch_upload_cmi5_course');
    formData.append('moodlewsrestformat', 'json');
    if (course.courseid) {
      formData.append('courseid', course.courseid);
    } else if (course.courseName) {
      formData.append('courseid', course.courseName);
    } else {
      throw Error('No course id or course name was provided');
    }
    formData.append('sectionid', course.sectionid);
    formData.append('filename', path.basename(zipPath));
    formData.append('modulename', course.modulename);

    const response = await axios.post(url, formData, {
      headers: formData.getHeaders(),
    });

    console.log('update response: ', response.data);

    return response.data;
  }

  private async updateCourse(course: MoodleCourse, zipPath: string) {
    const url = `${this.baseUrl}/webservice/rest/server.php`;

    const formData = new FormData();
    formData.append('file', fs.createReadStream(zipPath));
    formData.append('wstoken', this.wstoken);
    formData.append('wsfunction', 'mod_cmi5launch_update_cmi5_course');
    formData.append('moodlewsrestformat', 'json');
    if (course.courseid) {
      formData.append('courseid', course.courseid);
    } else if (course.courseName) {
      formData.append('courseid', course.courseName);
    } else {
      throw Error('No course id or course name was provided');
    }
    formData.append('sectionid', '1');
    formData.append('filename', path.basename(zipPath));
    formData.append('cmid', course.cmi5id);
    formData.append('modulename', course.modulename);

    const response = await axios.post(url, formData, {
      headers: formData.getHeaders(),
    });

    console.log('upload response: ', response.data);

    return response.data;
  }

  public async uploadCourse(
    courseData: CourseData,
    auMappingService: AuMappingService,
    zipPath: string,
    applyAuMappings = false,
    moodleSectionId = 0,
    moodleCourseId?: string,
    moodleCourseName?: string,
  ) {
    let existingCourse: MoodleCourse | null = null;
    try {
      const possibleCourses = await this.getCourse(courseData.courseTitle);
      if (possibleCourses.length > 0) {
        // This means we are updating a course
        existingCourse = possibleCourses[0];
      }
    } catch (error: any) {
      if (error.response && error.response.status === 404) {
        // Ignore 404
        console.log('Could not find cmi5 course on moodle');
      } else {
        console.error(
          'Error getting courses',
          this.baseUrl,
          courseData.courseTitle,
        );
        return;
      }
    }

    if (existingCourse) {
      // Update existing moodle course
      console.log('Course already exists:', existingCourse.cmi5id);
      console.log(
        'Course update currently not supported, please delete from moodle and rerurn',
        existingCourse.cmi5id,
      );

      // existingCourse.modulename = courseData.courseTitle;
      // this.updateCourse(existingCourse, zipPath);
    } else {
      console.log('Creating a new course');

      // Create new moodle course
      const newCourse: MoodleCourse = {
        cmi5id: '',
        sectionid: moodleSectionId,
        courseName: moodleCourseName,
        courseid: moodleCourseId,
        modulename: courseData.courseTitle,
      };
      this.createCourse(newCourse, zipPath);
    }

    if (applyAuMappings) {
      await auMappingService.resolveAllAus(courseData);
    }
  }
}
