import { CourseAU, CourseData } from '@rapid-cmi5/cmi5-build-common';
import { AxiosRequestConfig, isAxiosError } from 'axios';

import { createAuMappingName } from '../commands/generateAuMappings';
import { generateAuId, generateBlockId } from '@rapid-cmi5/cmi5-build/backend';
import {
  Cmi5AUMapping,
  Cmi5AUMappingApiFactory,
  Cmi5AuMappingUpdate,
  RangeContentScenariosApiFactory,
} from '../../../../libs/frontend/clients/devops-api/src/lib';
import path from 'path';

type Scenario = { scenarioName?: string; scenarioUUID?: string };

export interface AuMappingServiceDeps {
  baseUrl: string;
  jwt: string;
}

export function constructOpendashAuID(
  openDashendpoint: string,
  openDashUuid: string,
  au: CourseAU,
): string {
  const auPath = au.dirPath || '';
  return (
    openDashendpoint +
    '/' +
    path.join(
      'service-arch-api/lms/v1/cmi5/course/',
      openDashUuid,
      '/0/compiled_course/blocks/',
      auPath,
      'index.html',
    )
  );
}

export class AuMappingService {
  private cmi5Client;
  private scenarioClient;
  private options;

  constructor({ baseUrl, jwt }: AuMappingServiceDeps) {
    this.cmi5Client = Cmi5AUMappingApiFactory(undefined, baseUrl);
    this.scenarioClient = RangeContentScenariosApiFactory(undefined, baseUrl);

    this.options = {
      headers: {
        Authorization: `Bearer ${jwt}`,
      },
    } as AxiosRequestConfig;
  }

  async resolveAllAus(
    courseData: CourseData,
    openDashEndpoint: string | null = null,
    openDashUuid: string | null = null,
  ) {
    // everytime you create a new version of the course
    // the auid has a uuid in it that is generated by opendash

    for (const block of courseData.blocks) {
      for (const au of block.aus) {
        let auId;

        if (openDashUuid && openDashEndpoint) {
          auId = constructOpendashAuID(openDashEndpoint, openDashUuid, au);
        } else {
          const blockId = generateBlockId({
            courseId: courseData.courseId,
            blockName: block.blockName,
          });
          auId = generateAuId({
            blockId: blockId,
            auName: au.auName,
          });
        }

        if (!au.rangeosScenarioUUID && !au.rangeosScenarioName) {
          console.log(`\t⚠️  No scenarios associated with AU ID: ${auId}`);
          continue;
        }

        console.log(`\tRegistering scenarios for AU ID: ${auId}`);

        // We need to support the case in which a scenario name is given, this is for courses which
        // need to be on multiple deployments
        const scenario: Scenario = {
          scenarioName: au.rangeosScenarioName,
          scenarioUUID: au.rangeosScenarioUUID,
        };

        const scenarioUUID = await this.getSceanrioUUID(scenario);
        if (!scenarioUUID) {
          console.log(`\t⚠️  Cannot proceed without a scenario UUID`);
          return;
        }

        await this.resolveAuMapping(
          auId,
          scenarioUUID,
          createAuMappingName(
            courseData.courseTitle,
            block.blockName,
            au.auName,
          ),
        );
      }
    }
  }

  async getSceanrioUUID(scenario: Scenario) {
    if (!scenario.scenarioUUID && !scenario.scenarioName) {
      console.warn('No UUID or name provided for scenario lookup');
      return;
    }
    if (scenario.scenarioUUID) {
      try {
        const res = await this.scenarioClient.scenariosRetrieve(
          scenario.scenarioUUID,
          this.options,
        );

        if (!res.data.uuid) return;

        return scenario.scenarioUUID;
      } catch (error) {
        console.log(
          'Could not find scenario based on UUID, will try using name instead',
          error,
        );
      }
      // now ensure that his actually exists, if not fall back on the scenario name
    }

    if (scenario.scenarioName) {
      try {
        const res = await this.scenarioClient.scenariosList(
          undefined,
          scenario.scenarioName,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          this.options,
        );
        const scenarioRes = res.data?.data?.[0];

        if (!scenarioRes?.uuid) return;
        return scenarioRes.uuid;
      } catch (error) {
        if (isAxiosError(error) && error.response?.status === 404) {
          console.log('Scenario does not exist');

          return;
        }

        console.log('General error');
        return;
      }
    }

    return;
  }
  async resolveAuMapping(
    auId: string,
    scenarioUUID: string,
    mappingName: string,
  ) {
    let existingMapping: Cmi5AUMapping | undefined;

    try {
      const res = await this.cmi5Client.cmi5AuMappingRetrieve(
        auId,
        this.options,
      );

      existingMapping = res.data;
    } catch (error) {
      if (isAxiosError(error) && error.response?.status === 404) {
        console.log('mapping does not exist');
      } else {
        console.log('General error: ', error);
        return;
      }
    }

    // No new course, only updated scenario
    // The opendash course uuid did not change
    if (existingMapping) {
      const oldUUID = existingMapping.scenarios[0];
      if (oldUUID !== scenarioUUID) {
        const cmi5update: Cmi5AuMappingUpdate = {
          scenarios: [scenarioUUID],
        };
        console.log('\tExisting mapping, updated');

        await this.cmi5Client.cmi5AuMappingUpdate(
          auId,
          cmi5update,
          this.options,
        );
      } else {
        console.log('\tNo update needed');
      }
    }
    // New opendash course has been uploaded, au mapping has changed
    else {
      // We need a way to safely delete au mappings once the opendash course uuid changes
      // const oldMappings = allAuMappings.filter((m) => m.name === mappingName);
      // for (const mapping of oldMappings) {
      //   await this.cmi5Client.cmi5AuMappingDelete(mapping.auId);
      // }
      const res = await this.cmi5Client.cmi5AuMappingCreate(
        {
          auId,
          name: mappingName,
          scenarios: [scenarioUUID],
        },
        this.options,
      );

      console.log('\t✅ Mapping Created : ', res.data.name);
    }
  }
}
