import { CourseData, RC5_FILENAME } from '@rapid-cmi5/cmi5-build-common';
import JSZip from 'jszip';
import { basename, dirname, join } from 'path-browserify';
import YAML from 'yaml';

export const COMPILED_COURSE_PREFIX = 'compiled_course/blocks';

/** Files generated by the deployment process that should not be imported into the repo. */
const EXCLUDED_AU_FILES = [
  'config.json',
  'cfg.json',
  'index.html',
  'favicon.ico',
];

export interface CourseZipPaths {
  /** Path under the prefix, preserving the original course folder name. Used to match against AU dir paths. */
  pathInZip: string;
  /** Path with the original course folder replaced by the new course name. Used for writing to the repo. */
  pathInRepo: string;
}

/**
 * Resolves the repo-relative path for a zip entry.
 * Returns null if the entry is not under the compiled course prefix.
 */
export function resolveCourseZipPaths(
  relativePath: string,
  newCourseName: string,
): CourseZipPaths | null {
  // We can throw away everything in the zip that is not markdown related
  // This includes stuff like the js and cmi5.xml, this will be regenerated later
  if (!relativePath.startsWith(COMPILED_COURSE_PREFIX)) return null;

  const pathUnderPrefix = relativePath.slice(COMPILED_COURSE_PREFIX.length + 1);
  const slashIndex = pathUnderPrefix.indexOf('/');
  const pathWithoutOrigCourse =
    slashIndex > 0 ? pathUnderPrefix.slice(slashIndex) : pathUnderPrefix;

  return {
    pathInZip: pathUnderPrefix,
    pathInRepo: join(newCourseName, pathWithoutOrigCourse),
  };
}

/**
 * Returns true if a file should be excluded from the import.
 * AU directories contain deployment-only files that are not part of the original course content.
 */
export function isExcludedAuFile(
  pathInZip: string,
  auDirPaths: string[],
): boolean {
  if (!EXCLUDED_AU_FILES.includes(basename(pathInZip))) return false;
  return auDirPaths.includes(dirname(pathInZip));
}

export async function getRc5Content(zip: JSZip) {
  const decoder = new TextDecoder('utf-8');

  const rc5Path = Object.keys(zip.files).find((path) =>
    path.endsWith(RC5_FILENAME),
  );

  if (!rc5Path) {
    throw new Error('No RC5.yaml file was found in the uploaded zip file');
  }

  const content = await zip.files[rc5Path].async('uint8array');
  const courseData: CourseData = YAML.parse(decoder.decode(content));
  return courseData;
}

export async function updateCourseData(
  courseData: CourseData,
  courseName: string,
  courseId: string,
  courseDescription: string,
) {
  const encoder = new TextEncoder();

  courseData.courseId = courseId;
  courseData.courseDescription = courseDescription;
  courseData.courseTitle = courseName;

  for (const block of courseData.blocks) {
    block.blockName = courseName;

    for (const au of block.aus) {
      const index = au.dirPath.indexOf('/');
      const oldCoursePathRemoved = index > 0 ? au.dirPath.slice(index) : '';

      au.dirPath = join(courseName, oldCoursePathRemoved);

      for (const slide of au.slides) {
        slide.filepath = join(au.dirPath, basename(slide.filepath));
      }
    }
  }

  return encoder.encode(YAML.stringify(courseData));
}
